### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/VectorQuery#1]
Make the arguments case insensitive.

https://vector.artsdatabanken.no/ogapi/codes/10.383493796825316/62.334786580315125/na

returning same results as

https://vector.artsdatabanken.no/ogapi/codes/10.383493796825316/62.334786580315125/NA

**Comment by jarped** [comment]
Fixed by https://github.com/Artsdatabanken/VectorQuery/commit/a664e51ded213d6b3389f2aaeb222f4759865fd3
